title: Composition Class WiSe2024

logo: 
description: website with materials for MHL Composition Class in Winter Semester 2024
show_downloads: true
github.is_project_page: false
theme: jekyll-theme-cayman 
