title: Laborstunden Komposition WiSe2024

logo: 
description: website with materials for MHL Laborstunden Komposition in Winter Semester 2024
show_downloads: true
github.is_project_page: false
theme: jekyll-theme-cayman 
